F11 cycle fullscreen
] add speed 0.1                 # scale playback speed.
[ add speed -0.1
د add speed 0.1                 # scale playback speed.
ج add speed -0.1
ض quit
َ quit-watch-later
ض {encode} quit 4
ح cycle pause                          # toggle pause/playback mode
× no-osd cycle-values osd-level 3 1    # cycle through OSD mode
خ show-progress
؛ show-progress
' cycle mute
ي cycle deinterlace
ق add sub-pos -1                       # move subtitles up
t add sub-pos +1                       # same as previous binding (discouraged)
Alt+k add sub-scale +0.1
Alt+j add sub-scale -0.1
Ctrl+g script-message-to seek_to toggle-seeker
Ctrl+ل script-message-to seek_to toggle-seeker
ر cycle sub-visibility
ت cycle sub                            # cycle through subtitles
ب cycle fullscreen                     # toggle fullscreen
MBTN_MID cycle sub-visibility

Shift+WHEEL_UP no-osd seek  1 exact
Shift+WHEEL_DOWN  no-osd seek -1 exact
Alt+WHEEL_UP no-osd seek  0.1 exact
Alt+WHEEL_DOWN  no-osd seek -0.1 exact

KP1 seek 10 absolute-percent
KP2 seek 20 absolute-percent
KP3 seek 30 absolute-percent
KP4 seek 40 absolute-percent
KP5 seek 50 absolute-percent
KP6 seek 60 absolute-percent
KP7 seek 70 absolute-percent
KP8 seek 80 absolute-percent
KP9 seek 90 absolute-percent
KP0 seek 0 absolute-percent

# -----------------------------------------------
# Scripts
# -----------------------------------------------

Ctrl+r script-binding quality_menu/reload
# F      script-binding quality_menu/video_formats_toggle
# Alt+f script-binding quality_menu/audio_formats_toggle
# uosc
F     script-binding quality_menu/video_formats_toggle #! Stream Quality > Video
Alt+f script-binding quality_menu/audio_formats_toggle #! Stream Quality > Audio

Meta+c script-binding copy-subtitle
Alt+Meta+c script-binding copy-time
Alt+Meta+C script-binding copy-time-in-seconds
