POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_PROMPT_ON_NEWLINE="true"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="λ "
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER="…"
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vi_mode dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time battery)

if [[ -n "$NVIM_LISTEN_ADDRESS" || -n "$VIM_TERMINAL" ]]; then
  SPACESHIP_CHAR_SYMBOL="» "
else
  SPACESHIP_CHAR_SYMBOL="λ "
fi
SPACESHIP_PROMPT_DEFAULT_PREFIX="@ "
SPACESHIP_USER_SHOW=false
SPACESHIP_HOST_SHOW=false

PURE_PROMPT_SYMBOL="λ"
