#!/bin/sh
# $XConsortium: xinitrc.cpp,v 1.4 91/08/22 11:41:34 rws Exp $

# VARIABLES
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
DEFAULT_SESSION=i3

# Synaptic options
synclient horiztwofingerscroll=1
synclient TapButton1=1

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
  xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
  xmodmap $usermodmap
fi

# Set up an icon tray
#stalonetray -c $HOME/.xmonad/stalonetrayrc &

case $1 in
  sway)
    exec sway
    ;;
  i3)
    exec i3
    ;;
  xmonad)
    xsetroot -cursor_name left_ptr
    setxkbmap -layout be
    exec xmonad
    ;;
  awesome)
    exec  awesome
    ;;
  *)
    exec  $DEFAULT_SESSION
    ;;
esac

# If the user lacks $HOME/GNUstep, install it:
if [ ! -f $HOME/GNUstep/Defaults/WindowMaker ]; then
  wmaker.inst
fi

# Test for cpp, which wmaker uses to process config files:
if [ ! -x /usr/bin/cpp ]; then
  NOCPP="--no-cpp"
fi

# Start the window manager:
if [ -z "$DESKTOP_SESSION" -a -x /usr/bin/ck-launch-session ]; then
  exec ck-launch-session /usr/bin/wmaker $NOCPP
else
  exec /usr/bin/wmaker $NOCPP
fi


# Personal:
xset +fp /usr/share/emacs/fonts
