lookahead=5
speedup=4
leadin=1
sub_timeout=5
skipmode=no
maxSkip=2.5
minSkip=1
skipdelay=0.8
directskip=no
exact_skip=yes
dropOnAVdesync=yes
ignorePattern=no
subPattern='^[#♯♩♪♬♫🎵🎶%[%(]+.*[#♯♩♪♬♫🎵🎶%]%)]+$'
