#!/bin/bash
gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
sed -i 's/gtk-application-prefer-dark-theme=[0-1]/gtk-application-prefer-dark-theme=0/' ~/.config/gtk-[34]*/settings.ini
