#!/usr/bin/env bash

mkdir -p ~/Pictures/Screenshots
FILENAME=~/Pictures/Screenshots/$(date +%F-%s).png

while getopts f:c: option; do
  case "${option}" in
  f) FRONTEND=${OPTARG} ;;
  c) COMMAND=${OPTARG} ;;
  esac
done

capture_screen() {
  if [[ $FRONTEND == sway ]]; then
    grim -t png $FILENAME
  else
    scrot -F $FILENAME
  fi
}

capture_window() {
  if [[ $FRONTEND == sway ]]; then
    grim -g "$(slurp)" -t png $FILENAME
  else
    sleep 0.2
    scrot -sF $FILENAME
  fi
}

case $COMMAND in
"fullscreen") capture_screen ;;
"window") capture_window ;;
"teiler") teiler ;;
esac
