#!/usr/bin/env bash

layouts_array=(us ara tr ir fr)

current_layouts=$(grep -m1 -i xkb_layout "$HOME/.config/sway/config" | sed 's/\s*xkb_layout //' | tr -d '"')
selected=$(printf '%s\n' "${layouts_array[@]}" |
  rofi -dmenu -i -multi-select -format 'p' -no-custom \
    -theme-str 'window {width: 40%;} listview {lines: 8;}' \
    -p "Select layout <S-Enter> $([[ -n "$current_layouts" ]] && echo "($current_layouts)")")
if [[ -n "$selected" ]]; then
  new_layouts=$(echo "$selected" | tr '\n' ',' | sed 's/,$//')
  sed -i "s/xkb_layout.*/xkb_layout $new_layouts/" "$HOME/.config/sway/config" &&
    swaymsg reload && killall -USR2 waybar &&
    rofi -e "✅ Layout(s) changed to: $new_layouts" -theme-str 'window {width: 30%;}'
fi
