#!/bin/bash

[[ -f ~/.silent_mode ]] && exit

DB=~/.newsbeuter/cache.db

mapfile -t urls < <(grep -Ev ' podcast|^#|^$' ~/.newsbeuter/urls | sed -E 's/^(.+) .*/\1/')

for u in "${urls[@]}"; do
  unread_feeds=$(sqlite3 "$DB" "SELECT COUNT(*) FROM rss_item WHERE unread = 1 AND feedurl LIKE '$u'" 2>/dev/null)
  [[ -z $unread_feeds ]] && unread_feeds=0
  unread_count=$((unread_count + unread_feeds))
done

html_escape() {
  echo "$1" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

list() {
  query="SELECT title FROM rss_item WHERE unread = 1 ORDER BY pubDate DESC LIMIT 20;"
  n=$(sqlite3 "$DB" "$query")
  html_escape "$n"
}

notify() {
  notify-send "  RSS Feeds" "$(list)"
}

# case $BLOCK_BUTTON in
# 1 ) notify-send "$(sqlite3 ~/.newsbeuter/cache.db "SELECT title FROM rss_item WHERE unread = 1 ORDER BY pubDate ASC LIMIT 30")" ;;
# esac

if [[ $unread_count -gt 0 ]]; then
  if [[ $1 == "i3blocks" ]]; then
    echo " ($unread_count)"
    echo "#f26522"
    case $BLOCK_BUTTON in
    1) notify ;;
    esac
  elif [[ $1 == "polybar" ]]; then
    echo "%{F#f26522} ($unread_count)%{F-}"
  elif [[ $1 == waybar ]]; then
    echo '{' \
      '"text":' \
      \""$unread_count"\" , '"tooltip":' \
      \""$(list | perl -pe 's/\n/\\n/g' | sed 's/\\n$//')"\" \
      '}' | jq --unbuffered --compact-output
  elif [[ $1 == "notify" ]]; then
    notify
  fi
fi
