MODULES= date kbd_layouts_i3ipc exchange {{- if eq .machine "home" }} music {{- end }}

all:
	@rustup default stable
	$(foreach module,$(MODULES),cargo build --release --package=$(module);)

install:
	@mkdir -p bar
	$(foreach module,$(MODULES),mv target/release/$(module) bar;)

uninstall:
	@rm -rf bar

clean:
	@rm -rf target
