[packages]
linux = [
  "zsh",
  "starship",
  "sway",
  "swaylock",
  "swayidle",
  "waybar",
  "rofi",
  "lazygit",
  "tmuxp",
  "tmux",
  "vim",
  "neovim",
  "micro",
  "btop",
  "nnn",
  "atuin",
  "wlsunset",
  "ripgrep",
  "git-delta",
  "bat",
  "zoxide",
  "eza",
  "wdisplays",
  "wob",
  "wl-clipboard",
  "grim",
  "slurp",
  "autotiling",
  "newsboat",
  "task",
  "taskwarrior-tui",
  "power-profiles-daemon",
  "light",
  "ddcutil",
  "nsxiv",
  "clang",
  "shfmt",
  "go",
  "jq",
]

arch = [
  "fd",
  "swaync",
  "bottom",
  "ttf-firacode-nerd",
  "ttf-nerd-fonts-symbols",
  "yazi",
  "gitui",
  "itools",
  "darkman",
  "python-qrcode",
  "ruff",
  "prettier",
  "python-sqlparse",
  "taplo-cli",
  "perl-tidy",
]

debian = [
  "sway-notification-center",
  "btm",
  "fd-find",
  "fonts-hosny-amiri",
  "fonts-firacode",
  "itools",
  "python3-qrcode",
]

fedora = [
  "fd-find",
  "swaync",
  "bottom",
  "amiri-fonts",
  "fira-code-fonts",
  "nerd-fonts-symbols",
]
