#!/usr/bin/env python

"""
Pandoc filter to convert babelshorthands.
"""

from pandocfilters import toJSONFilter, Para
import re

def shorthands(txt):
  txt = re.sub(r'--', '–', txt)
  txt = re.sub(r'---', '—', txt)
  txt = re.sub(r'\(\(', r'«', txt, flags=re.DOTALL)
  txt = re.sub(r'\)\)', r'»', txt, flags=re.DOTALL)
  return txt

def babelshorthands(key, value, format, meta):
  if key == 'Para':
    rvalue = []
    for v in value:
      if v['t'] == 'Str': rvalue.append({
        't': 'Str',
        'c': shorthands(v['c'])
        })
      else: rvalue.append(v)
    return Para(rvalue)

if __name__ == "__main__":
  toJSONFilter(babelshorthands)
